smtp_on: false
smtp_host: smtp.sendgrid.net
smtp_hostbackup: ''
smtp_port: '465'
smtp_protocol: ssl
smtp_username: alvar0hurtad0
smtp_password: Uno12358
smtp_from: ''
smtp_fromname: ''
smtp_allowhtml: '0'
smtp_test_address: ''
smtp_debugging: false
_core:
  default_config_hash: ZfbmfcSfeKOEssW5y01Z6rijotca6J_bKMFGQ1t0GD0
langcode: es
